# Generated by Django 4.0.3 on 2022-04-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_team_chore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_chore',
            name='content',
            field=models.TextField(verbose_name='Task Content'),
        ),
        migrations.AlterField(
            model_name='team_chore',
            name='date_due',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='team_chore',
            name='team_chore_name',
            field=models.CharField(max_length=100, verbose_name='Group Task Name'),
        ),
    ]
